// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QuoteType string

const (
	QuoteTypeQuote QuoteType = "quote"
	QuoteTypeNote  QuoteType = "note"
)

func (e *QuoteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuoteType(s)
	case string:
		*e = QuoteType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuoteType: %T", src)
	}
	return nil
}

type NullQuoteType struct {
	QuoteType QuoteType `json:"quote_type"`
	Valid     bool      `json:"valid"` // Valid is true if QuoteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuoteType) Scan(value interface{}) error {
	if value == nil {
		ns.QuoteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuoteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuoteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuoteType), nil
}

type Author struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Birth       pgtype.Date `db:"birth" json:"birth"`
	Death       pgtype.Date `db:"death" json:"death"`
	Description *string     `db:"description" json:"description"`
	ProfileUri  *string     `db:"profile_uri" json:"profile_uri"`
	// sometimes, an author is a user
	UserID    uuid.NullUUID `db:"user_id" json:"user_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}

type AuthorQuote struct {
	ID      uuid.UUID     `db:"id" json:"id"`
	QuoteID uuid.NullUUID `db:"quote_id" json:"quote_id"`
	// Sometimes the author(s) of a quote is not the author(s) of the work. For example, Michel Foucault wrote the preface of Anti-Oedipus and contributed a number of memorable quotes but it was Gilles Deleuze and Felix Guattari that authored the work.
	AuthorID  uuid.NullUUID `db:"author_id" json:"author_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}

type AuthorWork struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	WorkID    uuid.NullUUID `db:"work_id" json:"work_id"`
	AuthorID  uuid.NullUUID `db:"author_id" json:"author_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}

type Quote struct {
	ID            uuid.UUID     `db:"id" json:"id"`
	Type          NullQuoteType `db:"type" json:"type"`
	Body          *string       `db:"body" json:"body"`
	WorkID        uuid.NullUUID `db:"work_id" json:"work_id"`
	ContributorID uuid.NullUUID `db:"contributor_id" json:"contributor_id"`
	Likes         int32         `db:"likes" json:"likes"`
	CreatedAt     time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt     time.Time     `db:"deleted_at" json:"deleted_at"`
}

type QuoteTag struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	QuoteID   uuid.NullUUID `db:"quote_id" json:"quote_id"`
	TagID     uuid.NullUUID `db:"tag_id" json:"tag_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}

type RelatedQuote struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	Quote1ID  uuid.NullUUID `db:"quote1_id" json:"quote1_id"`
	Quote2ID  uuid.NullUUID `db:"quote2_id" json:"quote2_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}

type Tag struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Value     string    `db:"value" json:"value"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	Name             string      `db:"name" json:"name"`
	Email            *string     `db:"email" json:"email"`
	Birth            pgtype.Date `db:"birth" json:"birth"`
	Description      *string     `db:"description" json:"description"`
	ProfileUri       *string     `db:"profile_uri" json:"profile_uri"`
	HasAuthorProfile *bool       `db:"has_author_profile" json:"has_author_profile"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	DeletedAt        time.Time   `db:"deleted_at" json:"deleted_at"`
}

type UserQuote struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	UserID    uuid.NullUUID `db:"user_id" json:"user_id"`
	QuoteID   uuid.NullUUID `db:"quote_id" json:"quote_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}

type Work struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Title         string    `db:"title" json:"title"`
	YearPublished *int32    `db:"year_published" json:"year_published"`
	Description   *string   `db:"description" json:"description"`
	CoverUri      *string   `db:"cover_uri" json:"cover_uri"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt     time.Time `db:"deleted_at" json:"deleted_at"`
}

type WorkTag struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	WorkID    uuid.NullUUID `db:"work_id" json:"work_id"`
	TagID     uuid.NullUUID `db:"tag_id" json:"tag_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time     `db:"deleted_at" json:"deleted_at"`
}
