// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateQuote(ctx context.Context, arg CreateQuoteParams) error
	GetQuoteByID(ctx context.Context, quoteID uuid.UUID) (Quote, error)
	GetQuoteTags(ctx context.Context, quoteID uuid.NullUUID) ([]GetQuoteTagsRow, error)
	ListRecentQuotes(ctx context.Context, arg ListRecentQuotesParams) ([]Quote, error)
	ListUserPostedQuotes(ctx context.Context, userID uuid.NullUUID) ([]Quote, error)
	ListUserSavedQuotes(ctx context.Context, userID uuid.NullUUID) ([]Quote, error)
}

var _ Querier = (*Queries)(nil)
