// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createQuote = `-- name: CreateQuote :exec
INSERT INTO quotes (
  body,
  work_id,
  contributor_id
) VALUES (
  $1,
  $2,
  $3
)
`

type CreateQuoteParams struct {
	QuoteBody *string       `db:"quote_body" json:"quote_body"`
	WorkID    uuid.NullUUID `db:"work_id" json:"work_id"`
	UserID    uuid.NullUUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) error {
	_, err := q.db.Exec(ctx, createQuote, arg.QuoteBody, arg.WorkID, arg.UserID)
	return err
}

const getQuoteByID = `-- name: GetQuoteByID :one
SELECT id, type, body, work_id, contributor_id, likes, created_at, updated_at, deleted_at
FROM quotes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetQuoteByID(ctx context.Context, quoteID uuid.UUID) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteByID, quoteID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Body,
		&i.WorkID,
		&i.ContributorID,
		&i.Likes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuoteTags = `-- name: GetQuoteTags :many
SELECT 
  t.id,
  t.value
FROM 
  tags t
LEFT JOIN 
  quote_tags qt ON qt.tag_id = t.id
WHERE qt.quote_id = $1
`

type GetQuoteTagsRow struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Value string    `db:"value" json:"value"`
}

func (q *Queries) GetQuoteTags(ctx context.Context, quoteID uuid.NullUUID) ([]GetQuoteTagsRow, error) {
	rows, err := q.db.Query(ctx, getQuoteTags, quoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuoteTagsRow
	for rows.Next() {
		var i GetQuoteTagsRow
		if err := rows.Scan(&i.ID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentQuotes = `-- name: ListRecentQuotes :many
SELECT id, type, body, work_id, contributor_id, likes, created_at, updated_at, deleted_at 
FROM quotes
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListRecentQuotesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRecentQuotes(ctx context.Context, arg ListRecentQuotesParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listRecentQuotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Body,
			&i.WorkID,
			&i.ContributorID,
			&i.Likes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPostedQuotes = `-- name: ListUserPostedQuotes :many
SELECT id, type, body, work_id, contributor_id, likes, created_at, updated_at, deleted_at
FROM quotes 
WHERE contributor_id = $1
`

func (q *Queries) ListUserPostedQuotes(ctx context.Context, userID uuid.NullUUID) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listUserPostedQuotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Body,
			&i.WorkID,
			&i.ContributorID,
			&i.Likes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSavedQuotes = `-- name: ListUserSavedQuotes :many
SELECT id, type, body, work_id, contributor_id, likes, created_at, updated_at, deleted_at 
FROM quotes
WHERE
  quotes.id IN (
    SELECT user_quotes.quote_id 
    FROM user_quotes
    WHERE user_quotes.user_id = $1
  )
LIMIT 50
`

func (q *Queries) ListUserSavedQuotes(ctx context.Context, userID uuid.NullUUID) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listUserSavedQuotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Body,
			&i.WorkID,
			&i.ContributorID,
			&i.Likes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
